// ============================================================================
// ENGLISH LOCALIZATION — Organized by Screen
// ============================================================================

class AppLocalizationsEn {
  static const Map<String, String> strings = {

    // ==========================================================================
    // ONBOARDING (lib/view/onboarding/)
    // ==========================================================================
    'appTitle': 'Family Side',
    'brandName': 'Familyside',
    'getStarted': 'Get Started',
    'letsConnect': "Let's Connect",
    'skip': 'Skip',
    'chooseYourRole': 'Choose Your Role',
    'chooseLanguage': 'Choose Your Language',
    'selectPreferredLanguage': 'Select your preferred language',
    'roleDescription': 'Discover doctors, playgrounds, nurseries and family services near you.',
    'familyParent': 'Family/Parent',
    'serviceProvider': 'Service Provider',
    'mother': 'Mother',
    'father': 'Father',
    'relative': 'Relative',
    'onboarding1Title': 'Find Activities for Your Kids',
    'onboarding1Description': 'Discover doctors, playgrounds, nurseries and family services near you.',
    'onboarding2Title': 'Personalized Suggestions',
    'onboarding2Description': "Get recommendations based on your child's age.",
    'onboarding3Title': 'Trusted Parent Community',
    'onboarding3Description': 'Read reviews from parents and share your experience.',
    'onboarding4Title': 'Expert Care & Support',
    'onboarding4Description': "Connect with certified professionals for your family's well-being.",

    // ==========================================================================
    // AUTH — Shared (lib/view/family/auth/ & lib/view/service_provider/auth/)
    // ==========================================================================
    'signIn': 'Sign In',
    'signUp': 'Sign Up',
    'signInToAccount': 'Sign in to your account',
    'createAccount': 'Create your account',
    'email': 'Email',
    'enterEmail': 'Enter your email',
    'password': 'Password',
    'enterPassword': 'Enter your password',
    'confirmPassword': 'Confirm Password',
    'confirmYourPassword': 'Confirm your password',
    'name': 'Name',
    'enterName': 'Enter your name',
    'rememberMe': 'Remember me',
    'forgotPassword': 'Forgot Password?',
    'orContinueWith': 'Or, continue with',
    'dontHaveAccount': "Don't have an account? ",
    'alreadyHaveAccount': 'Already have an account? ',
    'otpVerification': 'OTP Verification',
    'enterOtpCode': 'Enter the 6-digit code sent to your email',
    'didntReceiveCode': "Didn't receive the code? ",
    'sending': 'Sending...',
    'resend': 'Resend',
    'verify': 'Verify',
    'forgotPasswordTitle': 'Forgot Password',
    'enterEmailToReset': 'Enter your email to reset your password',
    'sendOtp': 'Send OTP',
    'resetPassword': 'Reset Password',
    'enterNewPassword': 'Enter your new password',
    'newPassword': 'New Password',
    'enterNewPasswordHint': 'Enter new password',
    'confirmNewPassword': 'Confirm new password',
    'congratulations': 'Congratulations!',
    'passwordResetSuccess': "Password Reset successful! You'll be redirected to the sign in screen now",
    'login': 'Login',
    'signup': 'Sign Up',

    // ==========================================================================
    // FAMILY — Onboarding Steps (child info, interests, location, image)
    // ==========================================================================
    'tellUsAboutChild': 'Tell us about your Child',
    'continueText': 'Continue',
    'ddmmyyyy': 'dd/mm/yyyy',
    'noKidsAdded': 'No kids added yet',
    'addChildrenToContinue': 'Add your children to continue',
    'pleaseSaveOrCancel': 'Please save or cancel first',
    'edit': 'Edit',
    'expectedDueDate': 'Expected Due Date',
    'addedKids': 'Added Kids',
    'childLabel': 'Child',
    'genderLabel': 'Gender',
    'enterChildName': "Enter child's name",
    'boy': 'boy',
    'save': 'Save',
    'cancel': 'Cancel',
    'deleteChild': 'Delete Child',
    'areYouSureRemoveChild': 'Are you sure you want to remove this child?',
    'delete': 'Delete',
    'pleaseSaveOrCancelCurrentForm': 'Please save or cancel the current form',
    'profile': 'Profile',
    'uploadYourImage': 'Upload your image',
    'addPicture': 'Add Picture',
    'location': 'Location',
    'enterYourLocation': 'Enter your location',
    'interests': 'Interests',
    'whatActivitiesChildEnjoy': 'What activities does your\nchild enjoy?',
    'enterYourInterest': 'Enter your interest',
    'noInterestsAvailable': 'No interests available',

    // ==========================================================================
    // FAMILY — HOME (lib/view/family/home/)
    // ==========================================================================
    'recommendedForYou': 'Recommended for You',
    'noRecommendedItems': 'No recommended items found',
    'eventsNearYou': 'Events Near You',
    'noEventsNearYou': 'No events found near you',
    'subCategories': 'Sub-categories',
    'noSubCategories': 'No sub-categories found',
    'searchHint': 'Search...',
    'seeAll': 'See All',
    'retry': 'Retry',
    'noItemsFound': 'No items found',
    'noResultsMatchSearch': 'No results match your search',
    'clearSearch': 'Clear search',
    'clearFilters': 'Clear filters',
    'saved': 'Saved',
    'activity': 'Activity',
    'events': 'Events',
    'gifts': 'Gifts',

    // ==========================================================================
    // FAMILY — EXPLORER (lib/view/family/explorer/)
    // ==========================================================================
    'explore': 'Explore',
    'noPlacesFound': 'No places found in this category',
    'noLocation': 'No location',
    'relatedEvents': 'Related Events',
    'giftIdeas': 'Gift ideas',
    'reviews': 'Reviews',
    'showLess': 'Show less',
    'readMore': 'Read more',
    'leaveReview': 'Leave a review',
    'welcomeGiftDescription': 'Welcome to our specialized gift, designed to offer children a safe, engaging, and enriching experience.',
    'accessToAllActivities': 'Access to all activities',
    'allMaterialsProvided': 'All materials provided',
    'duration1_5Hours': 'Duration: 1.5 Hours',
    'toddlers_3_5': 'Toddlers (3-5)',
    'kids_6_12': 'Kids (6-12)',
    'gift': 'Gift',
    'giftIdea': 'Gift idea',
    'linkCopied': 'Link copied to clipboard!',
    'claimVoucher': 'Claim Voucher',
    'voucherClaimedSuccess': 'Your voucher has been claimed and added to your wallet successfully!',
    'writeReview': 'Write review',
    'selectRecommendation': 'Select recommendation',
    'clickToUploadPhotos': 'Click to upload photos',
    'reviewSubmittedSuccess': 'Review submitted successfully!',
    'reviewSubmitFailed': 'Failed to submit review. Please try again.',

    // ==========================================================================
    // FAMILY — SEARCH (lib/view/family/search/)
    // ==========================================================================
    'forYou': 'For you',
    'nearYou': 'Near you',
    'noResultsFor': 'No results found for',
    'allAges': 'All ages',

    // ==========================================================================
    // FAMILY — GIFT (lib/view/family/gift/)
    // ==========================================================================
    'allGifts': 'All Gifts',
    'locationNotSet': 'Location not set',
    'searchPlanner': 'Search Planner...',
    'searchResult': 'Search Result',
    'noGiftsFound': 'No gifts found',
    'giftList': 'Gift List',
    'failedToLoadListItems': 'Failed to load list items',
    'yourGiftList': 'Your gift list',
    'noGiftsInList': 'No gifts in this list yet',
    'removeGiftConfirm': 'Are you sure you want to remove this from the list?',
    'myGiftList': 'My gift list',
    'createList': 'Create list',
    'failedToLoadGiftLists': 'Failed to load gift lists',
    'noGiftListsYet': 'No gift lists yet',
    'createFirstList': 'Create your first list to get started!',
    'giftsSavedInsideLists': 'Gifts saved inside your gift lists',
    'savedGiftsWithoutList': 'Saved gifts without a list',
    'giftsNotInAnyList': "Gifts you saved but didn't add to any list yet",
    'general': 'General',
    'createNewList': 'Create new list',
    'forTheOccasion': 'For the occasion',
    'birthday': 'Birthday',
    'christmas': 'Christmas',
    'anniversary': 'Anniversary',
    'pleaseEnterListName': 'Please enter a list name',
    'uploadListCoverImage': 'Upload list cover image',
    'tapToChange': 'Tap to change',
    'pngJpg': 'PNG, JPG',
    'failedToCreateList': 'Failed to create list. Please try again.',
    'nameOfTheList': 'Name of the list',
    'editListDetails': 'Edit list Details',
    'addGiftToList': 'Add gift to list',
    'allItemsAlreadyInList': 'All items are already in this list',
    'addToGiftList': 'Add to Gift list',
    'enterYourName': 'Enter Your name',
    'writeMessageHere': 'write message here....',
    'create': 'Create',
    'applyFilter': 'Apply Filter',
    'clearAll': 'Clear all',

    // ==========================================================================
    // FAMILY — NOTIFICATION (lib/view/family/notification/)
    // ==========================================================================
    'notifications': 'Notifications',
    'markAllAsRead': 'Mark all as read',
    'failedToMarkAllRead': 'Failed to mark all as read',
    'failedToLoadNotifications': 'Failed to load notifications',
    'noNotifications': 'No notifications yet',

    // ==========================================================================
    // FAMILY — PROFILE (lib/view/family/profile/)
    // ==========================================================================
    'changePassword': 'Change Password',
    'editProfile': 'Edit Profile',
    'childInformation': 'Child Information',
    'privacyPolicy': 'Privacy policy',
    'contactSupport': 'Contact Support',
    'yourSuggestions': 'Your Suggestions',
    'errorLoadingProfile': 'Error loading profile',
    'activities': 'Activities',
    'invitedFamily': 'Invited Family',
    'giftsShared': 'Gifts Shared',
    'generalSettings': 'General settings',
    'logOut': 'Log Out',
    'areYouSureLogOut': 'Are you sure you want to log out?',
    'noReviewsYet': 'No reviews yet',
    'reviewsAppearHere': 'Your reviews will appear here once you write some',
    'suggested': 'Suggested',
    'noSuggestionsYet': 'No suggestions yet',
    'suggestionsAppearHere': 'Suggestions will appear here once available',
    'noKidsAddedYet': 'No kids added yet',
    'addChildrenToUpdate': 'Add your children to update your profile',
    'addChild': 'Add Child',
    'noDobSet': 'No DOB set',
    'addMoreKids': 'Add more kids',
    'pleaseSelectDueDate': 'Please select due date',
    'childInfoUpdatedSuccess': 'Child information updated successfully',
    'failedToUpdateChild': 'Failed to update child information',
    'supportRequestSuccess': 'Support request submitted successfully',
    'failedToSubmitSupport': 'Failed to submit support request',
    'yourEmail': 'Your Email',
    'yourLocation': 'Your Location',
    'problemDetails': 'Problem details',
    'describeQueryHere': 'Describe your query here....',
    'submit': 'Submit',
    'passwordChangedSuccess': 'Password changed successfully',
    'failedToChangePassword': 'Failed to change password',
    'changePasswordLower': 'Change password',
    'enterCurrentPassword': 'Enter current password',
    'confirmNewPasswordHint': 'Confirm new password',
    'update': 'Update',
    'profileUpdatedSuccess': 'Profile updated successfully',
    'failedToUpdateProfile': 'Failed to update profile',
    'editProfileLower': 'Edit profile',
    'enterYourEmailHint': 'Enter your email',
    'enterYourLocationHint': 'Enter your location',
    'profileSetup': 'Profile setup',
    'helpUsConnect': 'Help us to connect more\nabout your business',
    'addMoreSocial': 'Add more social',
    'selectPlatform': 'Select Platform',
    'websiteLink': 'Website Link',
    'enterBusinessWebsite': 'Enter your Business website link',
    'exFacebookInstagram': 'ex. facebook, instagram',
    'facebook': 'Facebook',
    'instagram': 'Instagram',
    'twitter': 'Twitter',
    'linkedin': 'LinkedIn',
    'youtube': 'YouTube',
    'tiktok': 'TikTok',
    'pinterest': 'Pinterest',
    'snapchat': 'Snapchat',

    // ==========================================================================
    // FAMILY — NAV BAR (lib/view/family/family_main_nav_bar_screen.dart)
    // ==========================================================================
    'home': 'Home',
    'search': 'Search',

    // ==========================================================================
    // SP — HOME (lib/view/service_provider/home/)
    // ==========================================================================
    'failedToLoadData': 'Failed to load data',
    'pullDownToRefresh': 'Pull down to refresh',
    'user': 'User',
    'upcomingEvents': 'Upcoming events',
    'noUpcomingEvents': 'No upcoming events found',
    'topService': 'Top service',
    'noTopServices': 'No top services found',
    'welcomeBack': 'Welcome back',

    // ==========================================================================
    // SP — MANAGE (lib/view/service_provider/manage/)
    // ==========================================================================
    'manage': 'Manage',
    'pullDownToRetry': 'Pull down to retry',
    'nothingFound': 'Nothing found',
    'failedToLoadDetails': 'Failed to load details',
    'subCategoriesLabel': 'Sub-categories',
    'tags': 'Tags',
    'selectOpeningDays': 'Select Opening Days',
    'pleaseFillName': 'Please fill the name',
    'pleaseSelectCategory': 'Please select a category',
    'pleaseEnterPrice': 'Please enter a price',
    'pleaseSelectDate': 'Please select a date',
    'itemUpdatedSuccess': 'updated successfully',
    'failedToViewItem': 'Failed to update',
    'enterItemName': 'Enter name',
    'activityPrice': 'Activity Price',
    'enterAmount': 'Enter amount',
    'enterWebsiteLink': 'Enter website link',
    'whatsappNumber': "What's App Number",
    'enterPhoneNumber': 'Enter phone number',
    'enterYourEmailAddress': 'Enter your email address',
    'instagramLink': 'Instagram Link',
    'enterInstagramLink': 'Enter instagram link',
    'openingDays': 'Opening Days',
    'openingHours': 'Opening Hours',
    'enterDescription': 'Enter Description...',
    'searchOrAddTags': 'Search or add tags...',
    'popularTags': 'Popular tags',
    'selectedCount': 'selected',
    'addPhotos': 'Add Photos',
    'areYouSureDelete': 'Are you sure you want to delete?',
    'yes': 'Yes',
    'no': 'No',

    // ==========================================================================
    // SP — CREATE (lib/view/service_provider/create_section/)
    // ==========================================================================
    'whatWouldYouLikeToCreate': 'What Would You Like to Create?',
    'selectCreateType': 'Select whether you want to create an activity or an event.',
    'addEvent': 'Add event',
    'addNewEvent': 'Add New Event',
    'addEventSubtitle': 'Fill all the necessary details for adding a new event',
    'enterYourEventName': 'Enter your event name',
    'addActivity': 'Add activity',
    'addNewActivity': 'Add New Activity',
    'addActivitySubtitle': 'Fill all the necessary details for adding a new activity',
    'enterYourActivityName': 'Enter your activity name',
    'addGift': 'Add gift',
    'addNewGift': 'Add New Gift',
    'addGiftSubtitle': 'Fill all the necessary details for adding a new gift',
    'enterYourGiftName': 'Enter your gift name',
    'autoFillFromFlyer': 'Auto-fill from Flyer',
    'aiReadingFlyer': 'AI is reading your flyer...',
    'aiMayTakeSeconds': 'This may take a few seconds',
    'flyerParsedSuccess': 'Flyer parsed successfully! Review and submit.',
    'flyerParseFailed': 'Failed to parse flyer. Please try again.',
    'pleaseFillAllRequired': 'Please fill all required fields',
    'eventCreatedSuccess': 'Event created successfully',
    'activityCreatedSuccess': 'Activity created successfully',
    'giftCreatedSuccess': 'Gift created successfully',
    'failedToCreateEvent': 'Failed to create event',
    'failedToCreateActivity': 'Failed to create activity',
    'failedToCreateGift': 'Failed to create gift',
    'pleaseSelectCategoryFirst': 'Please select a category',
    'enterAmountHint': '\$00',
    'enterDateHint': 'yyyy-mm-dd',
    'enterTimeHint': 'hh:mm',
    'submitEvent': 'Submit event',
    'submitActivity': 'Submit activity',
    'submitGift': 'Submit gift',
    'selectCategory': 'Select category',
    'selectDays': 'Select days',
    'done': 'Done',

    // ==========================================================================
    // SP — ANALYTICS (lib/view/service_provider/analytics/)
    // ==========================================================================
    'analytics': 'Analytics',
    'profileViews': 'Profile Views',
    'userEngagement': 'User engagement',
    'totalActivities': 'Total Activities',
    'platformReach': 'Platform Reach',
    'categories': 'Categories',
    'suggestionsForYou': 'Suggestions For You',

    // ==========================================================================
    // SP — PROFILE (lib/view/service_provider/profile/)
    // ==========================================================================
    'subscription': 'Subscription',
    'loading': 'Loading...',
    'localContributor': 'Local Contributor',
    'contributeAndGrow': 'Contribute and Grow Your Level',
    'addEventButton': 'Add Event',
    'addActivityButton': 'Add Activity',
    'profileUpdatedSuccessfully': 'Profile updated successfully',
    'failedToUpdateProfileSp': 'Failed to update profile',
    'enterLocation': 'Enter location',
    'passwordChangedSuccessfully': 'Password changed successfully',
    'failedToChangePasswordSp': 'Failed to change password',
    'paymentProcessing': 'Payment processing...',
    'paymentMethod': 'Payment method',
    'totalAmount': 'Total Amount',
    'selectPaymentMethod': 'Select your payment method',
    'cardHolderName': 'Card holder name',
    'yourName': 'Your name',
    'enterCardHolderName': 'Enter card holder name',
    'cardNumber': 'Card number',
    'enterCardNumber': 'Enter card number',
    'invalidCardNumber': 'Invalid card number',
    'validUntil': 'Valid until',
    'enterExpiryDate': 'Enter expiry date',
    'invalidDate': 'Invalid date',
    'cvv': 'CVV',
    'enterCvv': 'Enter CVV',
    'invalidCvv': 'Invalid CVV',
    'saveCardForFuture': 'Save card data for future payments',
    'proceedToConfirm': 'Proceed to confirm',
    'free': 'Free',
    'startSimple': 'Start Simple',
    'startForFree': 'Start For Free',
    'createBusinessProfile': 'Create your business profile',
    'basicInfoAndPhotos': 'Basic info and photos',
    'basicVisibility': 'Basic Visibility',
    'smart': 'Smart',
    'growThroughCommunity': 'Grow Through Your Community',
    'goPremium': 'Go Premium',
    'allPremiumFeatures': 'All premium features',
    'maximumVisibility': 'Maximum visibility',
    'eventsAndGifts': 'Events & Gifts',
    'directContact': 'Direct contact',
    'joinByContributing': 'Join By Contributing To The Community',
    'offeringBenefitsToContributors': 'By Offering Benefits to Top Contributors',
    'theyDiscoverBusiness': 'They discover your business',
    'theyRecommend': 'They recommend it',
    'theyBringCustomers': 'They bring new customers',
    'benefitsForThemGrowthForYou': 'Benefits For Them, Growth For You',
    'freeCoffeeOrDrink': 'Free Coffee Or Drink',
    'freeDessert': 'Free Dessert',
    'freeTrial': 'Free Trial',
    'specialDiscount': 'Special Discount (10% - 20%)',
    'smallGiftForKids': 'Small Gift for kids',
    'familyOffers': 'Family Offers',
    'earlyAccess': 'Early Access',
    'premium': 'Premium',
    'allFeaturesIncluded': 'All features included',
    'growWithLocalFamily': 'Grow With Your Local\nFamily Community',
    'beDiscoveredTagline': 'Be discovered . Be recommended . Grow Faster',
    'canChangePlanAnytime': 'You can change your plan anytime',
    'featureRequest': 'Feature Request',
    'bugReport': 'Bug Report',
    'uiImprovement': 'UI Improvement',
    'other': 'Other',
    'type': 'Type',
    'title': 'Title',
    'enterShortTitle': 'Enter a short title',
    'suggestion': 'Suggestion',
    'describeSuggestion': 'Describe your suggestion in detail...',
    'wereHereToHelp': "We're here to help",
    'teamRespondsWithin24': 'Our team typically responds within 24 hours.',
    'subject': 'Subject',
    'enterSubject': 'Enter subject',
    'message': 'Message',
    'describeIssue': 'Describe your issue...',
    'sendMessage': 'Send Message',

    // ==========================================================================
    // SP — NAV BAR (lib/view/service_provider/sp_main_nav_bar_screen.dart)
    // ==========================================================================

    // ==========================================================================
    // SHARED (lib/view/widgets/)
    // ==========================================================================
    'enterNameOfLocation': 'Enter the name of the Location',
    'searchDots': 'Search ...',
    'share': 'Share',
    'english': 'English',
    'italian': 'Italiano',
    'language': 'Language',
    'settings': 'Settings',

    // ==========================================================================
    // COMMON / SHARED ACROSS SCREENS
    // ==========================================================================
    'ok': 'OK',
    'confirm': 'Confirm',
    'description': 'Description',
    'tag': 'Tag',
    'price': 'Price',
    'date': 'Date',
    'time': 'Time',
    'category': 'Category',
    'optional': '(Optional)',
    'required': '(Required)',
    'error': 'Error',
    'noInternet': 'No internet! Please check your internet connection.',
    'sessionExpired': 'Session expired. Please log in again.',
    'failedToCreate': 'Failed to create',
    'createdSuccessfully': 'created successfully',
    'updatedSuccessfully': 'updated successfully',
    'addedToList': 'Added to',
    'couldNotAddToList': 'Could not add to this list. Please try again.',
    'failedToAddGift': 'Failed to add gift to list. Please try again.',
    'failedToRemoveGift': 'Failed to remove gift. Please try again.',
    'failedToMarkAllAsRead': 'Failed to mark all as read',
    'highlyRecommended': 'Highly Recommended',
    'recommended': 'Recommended',
    'average': 'Average',
    'notSuitable': 'Not suitable',
    'education': 'Education',
    'music': 'Music',
    'sports': 'Sports',
    'dance': 'Dance',
    'outdoorPlay': 'Outdoor Play',
    'coding': 'Coding',
  };
}
