// ============================================================================
// ITALIAN LOCALIZATION — Organized by Screen
// ============================================================================

class AppLocalizationsIt {
  static const Map<String, String> strings = {

    // ONBOARDING
    'appTitle': 'Family Side',
    'brandName': 'Familyside',
    'getStarted': 'Inizia',
    'letsConnect': 'Collegiamoci',
    'skip': 'Salta',
    'chooseYourRole': 'Scegli il tuo ruolo',
    'chooseLanguage': 'Scegli la tua lingua',
    'selectPreferredLanguage': 'Seleziona la tua lingua preferita',
    'roleDescription': 'Scopri dottori, parchi giochi, asili e servizi familiari vicino a te.',
    'familyParent': 'Famiglia/Genitore',
    'serviceProvider': 'Fornitore di Servizi',
    'mother': 'Madre',
    'father': 'Padre',
    'relative': 'Parente',
    'onboarding1Title': 'Trova Attività per i Tuoi Bambini',
    'onboarding1Description': 'Scopri dottori, parchi giochi, asili e servizi familiari vicino a te.',
    'onboarding2Title': 'Suggerimenti Personalizzati',
    'onboarding2Description': 'Ricevi consigli basati sull\'età del tuo bambino.',
    'onboarding3Title': 'Comunità di Genitori Affidabile',
    'onboarding3Description': 'Leggi le recensioni dei genitori e condividi la tua esperienza.',
    'onboarding4Title': 'Cura e Supporto Esperti',
    'onboarding4Description': 'Connettiti con professionisti certificati per il benessere della tua famiglia.',

    // AUTH — Shared
    'signIn': 'Accedi',
    'signUp': 'Registrati',
    'signInToAccount': 'Accedi al tuo account',
    'createAccount': 'Crea il tuo account',
    'email': 'Email',
    'enterEmail': 'Inserisci la tua email',
    'password': 'Password',
    'enterPassword': 'Inserisci la tua password',
    'confirmPassword': 'Conferma Password',
    'confirmYourPassword': 'Conferma la tua password',
    'name': 'Nome',
    'enterName': 'Inserisci il tuo nome',
    'rememberMe': 'Ricordami',
    'forgotPassword': 'Password dimenticata?',
    'orContinueWith': 'Oppure, continua con',
    'dontHaveAccount': 'Non hai un account? ',
    'alreadyHaveAccount': 'Hai già un account? ',
    'otpVerification': 'Verifica OTP',
    'enterOtpCode': 'Inserisci il codice a 6 cifre inviato alla tua email',
    'didntReceiveCode': 'Non hai ricevuto il codice? ',
    'sending': 'Invio...',
    'resend': 'Reinvia',
    'verify': 'Verifica',
    'forgotPasswordTitle': 'Password Dimenticata',
    'enterEmailToReset': 'Inserisci la tua email per reimpostare la password',
    'sendOtp': 'Invia OTP',
    'resetPassword': 'Reimposta Password',
    'enterNewPassword': 'Inserisci la tua nuova password',
    'newPassword': 'Nuova Password',
    'enterNewPasswordHint': 'Inserisci nuova password',
    'confirmNewPassword': 'Conferma nuova password',
    'congratulations': 'Congratulazioni!',
    'passwordResetSuccess': 'Password reimpostata con successo! Verrai reindirizzato alla schermata di accesso',
    'login': 'Accedi',
    'signup': 'Registrati',

    // Onboarding Steps
    'tellUsAboutChild': 'Raccontaci del tuo Bambino',
    'continueText': 'Continua',
    'ddmmyyyy': 'gg/mm/aaaa',
    'noKidsAdded': 'Nessun bambino aggiunto ancora',
    'addChildrenToContinue': 'Aggiungi i tuoi bambini per continuare',
    'pleaseSaveOrCancel': 'Per favore salva o annulla prima',
    'edit': 'Modifica',
    'expectedDueDate': 'Data di parto prevista',
    'addedKids': 'Bambini aggiunti',
    'childLabel': 'Bambino',
    'genderLabel': 'Genere',
    'enterChildName': 'Inserisci il nome del bambino',
    'boy': 'maschio',
    'save': 'Salva',
    'cancel': 'Annulla',
    'deleteChild': 'Elimina Bambino',
    'areYouSureRemoveChild': 'Sei sicuro di voler rimuovere questo bambino?',
    'delete': 'Elimina',
    'pleaseSaveOrCancelCurrentForm': 'Per favore salva o annulla il modulo corrente',
    'profile': 'Profilo',
    'uploadYourImage': 'Carica la tua immagine',
    'addPicture': 'Aggiungi Foto',
    'location': 'Luogo',
    'enterYourLocation': 'Inserisci il tuo luogo',
    'interests': 'Interessi',
    'whatActivitiesChildEnjoy': 'Quali attività al tuo\nbambino piacciono?',
    'enterYourInterest': 'Inserisci il tuo interesse',
    'noInterestsAvailable': 'Nessun interesse disponibile',

    // FAMILY — HOME
    'recommendedForYou': 'Consigliati per Te',
    'noRecommendedItems': 'Nessun elemento consigliato trovato',
    'eventsNearYou': 'Eventi Vicino a Te',
    'noEventsNearYou': 'Nessun evento trovato vicino a te',
    'subCategories': 'Sottocategorie',
    'noSubCategories': 'Nessuna sottocategoria trovata',
    'searchHint': 'Cerca...',
    'seeAll': 'Vedi Tutto',
    'retry': 'Riprova',
    'noItemsFound': 'Nessun elemento trovato',
    'noResultsMatchSearch': 'Nessun risultato corrisponde alla tua ricerca',
    'clearSearch': 'Cancella ricerca',
    'clearFilters': 'Cancella filtri',
    'saved': 'Salvati',
    'activity': 'Attività',
    'events': 'Eventi',
    'gifts': 'Regali',
    'nothingSaved': 'Nessun elemento salvato trovato',

    // FAMILY — EXPLORER
    'explore': 'Esplora',
    'noPlacesFound': 'Nessun luogo trovato in questa categoria',
    'noLocation': 'Nessun luogo',
    'relatedEvents': 'Eventi Correlati',
    'giftIdeas': 'Idee Regalo',
    'reviews': 'Recensioni',
    'showLess': 'Mostra meno',
    'readMore': 'Leggi di più',
    'leaveReview': 'Lascia una recensione',
    'welcomeGiftDescription': 'Benvenuto nel nostro regalo specializzato, pensato per offrire ai bambini un\'esperienza sicura, coinvolgente e arricchente.',
    'accessToAllActivities': 'Accesso a tutte le attività',
    'allMaterialsProvided': 'Tutti i materiali forniti',
    'duration1_5Hours': 'Durata: 1,5 Ore',
    'toddlers_3_5': 'Bambini (3-5)',
    'kids_6_12': 'Bambini (6-12)',
    'gift': 'Regalo',
    'giftIdea': 'Idea Regalo',
    'linkCopied': 'Link copiato negli appunti!',
    'claimVoucher': 'Richiedi Voucher',
    'voucherClaimedSuccess': 'Il tuo voucher è stato richiesto e aggiunto al tuo portafoglio con successo!',
    'writeReview': 'Scrivi recensione',
    'selectRecommendation': 'Seleziona raccomandazione',
    'clickToUploadPhotos': 'Clicca per caricare foto',
    'reviewSubmittedSuccess': 'Recensione inviata con successo!',
    'reviewSubmitFailed': 'Invio recensione fallito. Riprova.',

    // FAMILY — SEARCH
    'forYou': 'Per te',
    'nearYou': 'Vicino a te',
    'noResultsFor': 'Nessun risultato trovato per',
    'allAges': 'Tutte le età',

    // FAMILY — GIFT
    'allGifts': 'Tutti i Regali',
    'locationNotSet': 'Luogo non impostato',
    'searchPlanner': 'Cerca Planner...',
    'searchResult': 'Risultato Ricerca',
    'noGiftsFound': 'Nessun regalo trovato',
    'giftList': 'Lista Regali',
    'failedToLoadListItems': 'Caricamento elementi lista fallito',
    'yourGiftList': 'La tua lista regali',
    'noGiftsInList': 'Nessun regalo in questa lista ancora',
    'removeGiftConfirm': 'Sei sicuro di voler rimuovere questo dalla lista?',
    'myGiftList': 'La mia lista regali',
    'createList': 'Crea lista',
    'failedToLoadGiftLists': 'Caricamento liste regali fallito',
    'noGiftListsYet': 'Nessuna lista regali ancora',
    'createFirstList': 'Crea la tua prima lista per iniziare!',
    'giftsSavedInsideLists': 'Regali salvati nelle tue liste',
    'savedGiftsWithoutList': 'Regali salvati senza lista',
    'giftsNotInAnyList': 'Regali che hai salvato ma non hai aggiunto a nessuna lista',
    'general': 'Generale',
    'createNewList': 'Crea nuova lista',
    'forTheOccasion': 'Per l\'occasione',
    'birthday': 'Compleanno',
    'christmas': 'Natale',
    'anniversary': 'Anniversario',
    'pleaseEnterListName': 'Inserisci il nome della lista',
    'uploadListCoverImage': 'Carica immagine coperta della lista',
    'tapToChange': 'Tocca per cambiare',
    'pngJpg': 'PNG, JPG',
    'failedToCreateList': 'Creazione lista fallita. Riprova.',
    'nameOfTheList': 'Nome della lista',
    'editListDetails': 'Modifica Dettagli Lista',
    'addGiftToList': 'Aggiungi regalo alla lista',
    'allItemsAlreadyInList': 'Tutti gli elementi sono già in questa lista',
    'addToGiftList': 'Aggiungi alla lista Regali',
    'enterYourName': 'Inserisci il tuo nome',
    'writeMessageHere': 'scrivi messaggio qui....',
    'create': 'Crea',
    'applyFilter': 'Applica Filtro',
    'clearAll': 'Cancella tutto',

    // FAMILY — NOTIFICATION
    'notifications': 'Notifiche',
    'markAllAsRead': 'Segna tutto come letto',
    'failedToMarkAllRead': 'Impossibile segnare tutto come letto',
    'failedToLoadNotifications': 'Caricamento notifiche fallito',
    'noNotifications': 'Nessuna notifica ancora',

    // FAMILY — PROFILE
    'changePassword': 'Cambia Password',
    'editProfile': 'Modifica Profilo',
    'childInformation': 'Informazioni Bambino',
    'privacyPolicy': 'Privacy Policy',
    'contactSupport': 'Contatta Supporto',
    'yourSuggestions': 'I Tuoi Suggerimenti',
    'errorLoadingProfile': 'Errore nel caricamento del profilo',
    'activities': 'Attività',
    'invitedFamily': 'Famiglie Invitate',
    'giftsShared': 'Regali Condivisi',
    'generalSettings': 'Impostazioni generali',
    'logOut': 'Esci',
    'areYouSureLogOut': 'Sei sicuro di voler uscire?',
    'noReviewsYet': 'Nessuna recensione ancora',
    'reviewsAppearHere': 'Le tue recensioni appariranno qui una volta scritte',
    'suggested': 'Suggerito',
    'noSuggestionsYet': 'Nessun suggerimento ancora',
    'suggestionsAppearHere': 'I suggerimenti appariranno qui quando disponibili',
    'noKidsAddedYet': 'Nessun bambino aggiunto ancora',
    'addChildrenToUpdate': 'Aggiungi i tuoi bambini per aggiornare il profilo',
    'addChild': 'Aggiungi Bambino',
    'noDobSet': 'Nessuna data di nascita impostata',
    'addMoreKids': 'Aggiungi altri bambini',
    'pleaseSelectDueDate': 'Seleziona la data',
    'childInfoUpdatedSuccess': 'Informazioni bambino aggiornate con successo',
    'failedToUpdateChild': 'Aggiornamento informazioni bambino fallito',
    'supportRequestSuccess': 'Richiesta di supporto inviata con successo',
    'failedToSubmitSupport': 'Invio richiesta di supporto fallito',
    'yourEmail': 'La Tua Email',
    'yourLocation': 'Il Tuo Luogo',
    'problemDetails': 'Dettagli del problema',
    'describeQueryHere': 'Descrivi la tua richiesta qui....',
    'submit': 'Invia',
    'passwordChangedSuccess': 'Password cambiata con successo',
    'failedToChangePassword': 'Cambio password fallito',
    'changePasswordLower': 'Cambia password',
    'enterCurrentPassword': 'Inserisci password attuale',
    'confirmNewPasswordHint': 'Conferma nuova password',
    'update': 'Aggiorna',
    'profileUpdatedSuccess': 'Profilo aggiornato con successo',
    'failedToUpdateProfile': 'Aggiornamento profilo fallito',
    'editProfileLower': 'Modifica profilo',
    'enterYourEmailHint': 'Inserisci la tua email',
    'enterYourLocationHint': 'Inserisci il tuo luogo',
    'profileSetup': 'Configurazione profilo',
    'helpUsConnect': 'Aiutaci a connetterti di più\nsul tuo business',
    'addMoreSocial': 'Aggiungi altro social',
    'selectPlatform': 'Seleziona Piattaforma',
    'websiteLink': 'Link Sito Web',
    'enterBusinessWebsite': 'Inserisci il link del sito web del tuo business',
    'exFacebookInstagram': 'es. facebook, instagram',
    'facebook': 'Facebook',
    'instagram': 'Instagram',
    'twitter': 'Twitter',
    'linkedin': 'LinkedIn',
    'youtube': 'YouTube',
    'tiktok': 'TikTok',
    'pinterest': 'Pinterest',
    'snapchat': 'Snapchat',

    // FAMILY — NAV BAR
    'home': 'Home',
    'search': 'Cerca',

    // SP — HOME
    'failedToLoadData': 'Caricamento dati fallito',
    'pullDownToRefresh': 'Trascina verso il basso per aggiornare',
    'user': 'Utente',
    'upcomingEvents': 'Prossimi eventi',
    'noUpcomingEvents': 'Nessun evento in arrivo trovato',
    'topService': 'Servizio top',
    'noTopServices': 'Nessun servizio top trovato',
    'welcomeBack': 'Bentornato',

    // SP — MANAGE
    'manage': 'Gestisci',
    'pullDownToRetry': 'Trascina verso il basso per riprovare',
    'nothingFound': 'Nessun elemento trovato',
    'failedToLoadDetails': 'Caricamento dettagli fallito',
    'subCategoriesLabel': 'Sottocategorie',
    'tags': 'Etichette',
    'selectOpeningDays': 'Seleziona Giorni di Apertura',
    'pleaseFillName': 'Inserisci il nome',
    'pleaseSelectCategory': 'Seleziona una categoria',
    'pleaseEnterPrice': 'Inserisci un prezzo',
    'pleaseSelectDate': 'Seleziona una data',
    'itemUpdatedSuccess': 'aggiornato con successo',
    'failedToViewItem': 'Aggiornamento fallito',
    'enterItemName': 'Inserisci nome',
    'activityPrice': 'Prezzo Attività',
    'enterAmount': 'Inserisci importo',
    'enterWebsiteLink': 'Inserisci link sito web',
    'whatsappNumber': 'Numero WhatsApp',
    'enterPhoneNumber': 'Inserisci numero di telefono',
    'enterYourEmailAddress': 'Inserisci il tuo indirizzo email',
    'instagramLink': 'Link Instagram',
    'enterInstagramLink': 'Inserisci link instagram',
    'openingDays': 'Giorni di Apertura',
    'openingHours': 'Orari di Apertura',
    'enterDescription': 'Inserisci Descrizione...',
    'searchOrAddTags': 'Cerca o aggiungi etichette...',
    'popularTags': 'Etichette popolari',
    'selectedCount': 'selezionate',
    'addPhotos': 'Aggiungi Foto',
    'areYouSureDelete': 'Sei sicuro di voler eliminare?',
    'yes': 'Sì',
    'no': 'No',

    // SP — CREATE
    'whatWouldYouLikeToCreate': 'Cosa Vorresti Creare?',
    'selectCreateType': 'Seleziona se vuoi creare un\'attività o un evento.',
    'addEvent': 'Aggiungi evento',
    'addNewEvent': 'Aggiungi Nuovo Evento',
    'addEventSubtitle': 'Compila tutti i dettagli necessari per aggiungere un nuovo evento',
    'enterYourEventName': 'Inserisci il nome dell\'evento',
    'addActivity': 'Aggiungi attività',
    'addNewActivity': 'Aggiungi Nuova Attività',
    'addActivitySubtitle': 'Compila tutti i dettagli necessari per aggiungere una nuova attività',
    'enterYourActivityName': 'Inserisci il nome dell\'attività',
    'addGift': 'Aggiungi regalo',
    'addNewGift': 'Aggiungi Nuovo Regalo',
    'addGiftSubtitle': 'Compila tutti i dettagli necessari per aggiungere un nuovo regalo',
    'enterYourGiftName': 'Inserisci il nome del regalo',
    'autoFillFromFlyer': 'Compila automaticamente dal volantino',
    'aiReadingFlyer': 'L\'AI sta leggendo il tuo volantino...',
    'aiMayTakeSeconds': 'Potrebbe richiedere qualche secondo',
    'flyerParsedSuccess': 'Volantino analizzato con successo! Rivedi e invia.',
    'flyerParseFailed': 'Analisi del volantino fallita. Riprova.',
    'pleaseFillAllRequired': 'Compila tutti i campi obbligatori',
    'eventCreatedSuccess': 'Evento creato con successo',
    'activityCreatedSuccess': 'Attività creata con successo',
    'giftCreatedSuccess': 'Regalo creato con successo',
    'failedToCreateEvent': 'Creazione evento fallita',
    'failedToCreateActivity': 'Creazione attività fallita',
    'failedToCreateGift': 'Creazione regalo fallita',
    'pleaseSelectCategoryFirst': 'Seleziona prima una categoria',
    'enterAmountHint': '00',
    'enterDateHint': 'gg/mm/aaaa',
    'enterTimeHint': 'hh:mm',
    'submitEvent': 'Invia evento',
    'submitActivity': 'Invia attività',
    'submitGift': 'Invia regalo',
    'selectCategory': 'Seleziona categoria',
    'selectDays': 'Seleziona giorni',
    'done': 'Fatto',

    // SP — ANALYTICS
    'analytics': 'Analisi',
    'profileViews': 'Visualizzazioni Profilo',
    'userEngagement': 'Engagement utenti',
    'totalActivities': 'Attività Totali',
    'platformReach': 'Raggiungimento Piattaforma',
    'categories': 'Categorie',
    'suggestionsForYou': 'Suggerimenti Per Te',

    // SP — PROFILE
    'subscription': 'Abbonamento',
    'loading': 'Caricamento...',
    'localContributor': 'Collaboratore Locale',
    'contributeAndGrow': 'Contribuisci e Cresci il Tuo Livello',
    'addEventButton': 'Aggiungi Evento',
    'addActivityButton': 'Aggiungi Attività',
    'profileUpdatedSuccessfully': 'Profilo aggiornato con successo',
    'failedToUpdateProfileSp': 'Aggiornamento profilo fallito',
    'enterLocation': 'Inserisci luogo',
    'passwordChangedSuccessfully': 'Password cambiata con successo',
    'failedToChangePasswordSp': 'Cambio password fallito',
    'paymentProcessing': 'Elaborazione pagamento...',
    'paymentMethod': 'Metodo di pagamento',
    'totalAmount': 'Importo Totale',
    'selectPaymentMethod': 'Seleziona il tuo metodo di pagamento',
    'cardHolderName': 'Nome intestatario',
    'yourName': 'Il tuo nome',
    'enterCardHolderName': 'Inserisci nome intestatario',
    'cardNumber': 'Numero carta',
    'enterCardNumber': 'Inserisci numero carta',
    'invalidCardNumber': 'Numero carta non valido',
    'validUntil': 'Valido fino al',
    'enterExpiryDate': 'Inserisci data scadenza',
    'invalidDate': 'Data non valida',
    'cvv': 'CVV',
    'enterCvv': 'Inserisci CVV',
    'invalidCvv': 'CVV non valido',
    'saveCardForFuture': 'Salva dati carta per pagamenti futuri',
    'proceedToConfirm': 'Procedi alla conferma',
    'free': 'Gratuito',
    'startSimple': 'Inizia Semplicemente',
    'startForFree': 'Inizia Gratis',
    'createBusinessProfile': 'Crea il tuo profilo aziendale',
    'basicInfoAndPhotos': 'Info base e foto',
    'basicVisibility': 'Visibilità Base',
    'smart': 'Smart',
    'growThroughCommunity': 'Cresci Attraverso la Community',
    'goPremium': 'Passa a Premium',
    'allPremiumFeatures': 'Tutte le funzionalità premium',
    'maximumVisibility': 'Visibilità massima',
    'eventsAndGifts': 'Eventi e Regali',
    'directContact': 'Contatto diretto',
    'joinByContributing': 'Unisciti Contribuendo alla Community',
    'offeringBenefitsToContributors': 'Offrendo Benefici ai Migliori Contributori',
    'theyDiscoverBusiness': 'Scoprono la tua attività',
    'theyRecommend': 'La raccomandano',
    'theyBringCustomers': 'Portano nuovi clienti',
    'benefitsForThemGrowthForYou': 'Benefici Per Loro, Crescita Per Te',
    'freeCoffeeOrDrink': 'Caffè O Bevanda Gratuita',
    'freeDessert': 'Dolce Gratuito',
    'freeTrial': 'Prova Gratuita',
    'specialDiscount': 'Sconto Speciale (10% - 20%)',
    'smallGiftForKids': 'Piccolo Regalo per bambini',
    'familyOffers': 'Offerte Famiglia',
    'earlyAccess': 'Accesso Anticipato',
    'premium': 'Premium',
    'allFeaturesIncluded': 'Tutte le funzionalità incluse',
    'growWithLocalFamily': 'Cresci Con La Tua\nCommunity Familiare Locale',
    'beDiscoveredTagline': 'Fati scoprire . Fati raccomandare . Cresci Più Velocemente',
    'canChangePlanAnytime': 'Puoi cambiare il tuo piano in qualsiasi momento',
    'featureRequest': 'Richiesta Funzionalità',
    'bugReport': 'Segnalazione Bug',
    'uiImprovement': 'Miglioramento UI',
    'other': 'Altro',
    'type': 'Tipo',
    'title': 'Titolo',
    'enterShortTitle': 'Inserisci un titolo breve',
    'suggestion': 'Suggerimento',
    'describeSuggestion': 'Descrivi il tuo suggerimento in dettaglio...',
    'wereHereToHelp': 'Siamo qui per aiutarti',
    'teamRespondsWithin24': 'Il nostro team risponde tipicamente entro 24 ore.',
    'subject': 'Oggetto',
    'enterSubject': 'Inserisci oggetto',
    'message': 'Messaggio',
    'describeIssue': 'Descrivi il tuo problema...',
    'sendMessage': 'Invia Messaggio',

    // SP — NAV BAR

    // SHARED
    'enterNameOfLocation': 'Inserisci il nome del luogo',
    'searchDots': 'Cerca ...',
    'share': 'Condividi',
    'english': 'English',
    'italian': 'Italiano',
    'language': 'Lingua',
    'settings': 'Impostazioni',

    // COMMON
    'ok': 'OK',
    'confirm': 'Conferma',
    'description': 'Descrizione',
    'tag': 'Etichetta',
    'price': 'Prezzo',
    'date': 'Data',
    'time': 'Ora',
    'category': 'Categoria',
    'optional': '(Opzionale)',
    'required': '(Obbligatorio)',
    'error': 'Errore',
    'noInternet': 'Nessuna connessione internet! Controlla la tua connessione.',
    'sessionExpired': 'Sessione scaduta. Effettua nuovamente l\'accesso.',
    'failedToCreate': 'Creazione fallita',
    'createdSuccessfully': 'creato con successo',
    'updatedSuccessfully': 'aggiornato con successo',
    'addedToList': 'Aggiunto a',
    'couldNotAddToList': 'Impossibile aggiungere a questa lista. Riprova.',
    'failedToAddGift': 'Aggiunta regalo alla lista fallita. Riprova.',
    'failedToRemoveGift': 'Rimozione regalo fallita. Riprova.',
    'failedToMarkAllAsRead': 'Impossibile segnare tutto come letto',
    'highlyRecommended': 'Fortemente Consigliato',
    'recommended': 'Consigliato',
    'average': 'Media',
    'notSuitable': 'Non adatto',
    'education': 'Educazione',
    'music': 'Musica',
    'sports': 'Sport',
    'dance': 'Danza',
    'outdoorPlay': 'Gioco all\'aperto',
    'coding': 'Programmazione',
  };
}
